title: Ruurd's Academic Homepage
theme: jekyll-theme-minimal
url: "https://ruurdkuiper.github.io"
baseurl: "/homepage"

defaults:
  - scope:
      path: ""
    values:
      layout: default
      author: Ruurd
